# Generated by Django 5.1.4 on 2024-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='id',
            new_name='conversation_id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='message_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
